import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import React, { useState, useEffect  } from 'react';
import Link from 'next/link'
import { AiFillEye, AiTwotoneEyeInvisible } from "react-icons/ai";
import { useRouter } from 'next/router'
import Cookies from "js-cookie";




export default function Home() {
  const router = useRouter();
  const [eyeicons, setEyeicons] = useState(false);
  const [loader, setLoader] = useState(false);
  
  const [email, setemail] = useState('');
  const [password, setPassword] = useState('');
  


const onsubmit = () =>{ 
  if(email && password){
  setLoader(true);
const requestOptions = {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          email: email,
          password: password
        })
    };
    fetch('/api/adminlogin', requestOptions)
        .then(response => response.json())
        .then(data => {          
        if(data.token){
          Cookies.set("token", data.token);
          router.push("/admin/dash");
          setLoader(false);
        }
          
        });
}
 }
 




  return (
    <>
      <Head>
        <title>shikhonschool-Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main>
        <div className="signin_main">

{loader ? 
<div class="lds-roller"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
: ""}
        
        
        <div className="signin_left" style={{backgroundPosition: 'center', backgroundRepeat: 'no-repeat', backgroundImage: "url(" + "https://static.vecteezy.com/system/resources/previews/015/732/277/non_2x/abstract-transparent-circles-with-shadow-on-white-grey-background-illustration-vector.jpg" + ")"}}>
        
        <div className="signin"> Sign In </div>
        <div className="signinform">
            <div className="input-container">
                <label>Email Address </label>
                <input type="text" value={email}  className="login_email" onChange={e => setemail(e.target.value)}  />
            </div>
            <div className="input-container">
                <label>Password </label>
                <input type={eyeicons ? "text" : "password"} name="pass" value={password} onChange={e => setPassword(e.target.value)} className="inputpasword_field" />
                <div className="eye_icon" onClick={()=>setEyeicons(!eyeicons)} >
                  { eyeicons ? <AiFillEye/> : <AiTwotoneEyeInvisible /> }
                </div>
            </div>
            <div className="input-remember">
                <input type="checkbox" value="lsRememberMe" /> &nbsp;
                <label htmlFor="rememberMe"> Remember me</label>
            </div>




            <div className="button-container">              
                  <input type="submit" value="Sign in" onClick={()=>onsubmit()}/>
            </div>

             </div>
            <div className="privacy_policy"> Privacy Policy | Contact </div>
   </div>
      

        <div className="signin_right">
          <div className="signin_company_name">Shikhon School</div>
          <img src="https://www.pngmart.com/files/7/Network-PNG-Free-Download.png" />
        </div>
        

      </div>
        
      </main>
    </>
  )
}
