import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import React, { useState, useEffect  } from 'react';
import Link from 'next/link'
import Leftdiv from './ass/Leftdiv';
import Topbar from './ass/Topbar';


export default function client_payment() {
  


  return (
    <>
      <Head>
        <title>Shikhon School_client_payment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
      

      <main>       
               

<Topbar/>

 
      <div className="main">
          <div className="left_side">
         <Leftdiv/>
         </div>



        <div className="right_side">
          client_payment
        </div>

      </div>


      </main>


    </>
  )
}
