import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import React, { useState, useEffect } from 'react';
import Link from 'next/link'
import Leftdiv from './ass/Leftdiv';
import Topbar from './ass/Topbar';
import { CiBoxList } from "react-icons/ci";
import Table from 'react-bootstrap/Table';
import axios from 'axios';

export default function Public_quize() {
  const [get_success_data, setGet_success_data] = useState([]);

  var a = 1;

  useEffect(() => {
    getdatashow();
  }, [])


  async function getdatashow() {

    await axios.get('/api/get_allquize')
      .then(response => {
        setGet_success_data(response.data.data)
      })
  }


  const quize_allowfunct = (data) => {

    const allowsss = data.actives === 0 ? 1 : 0;

    const dataa = {
      "allow": allowsss,
      "_id": data._id
    }
    axios.post('/api/quize_public_allow', dataa)
      .then(response => {
        getdatashow()
      })

  }





  

  return (
    <>
      <Head>
        <title>Shikhon School_public_quize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
      </Head>


      <main>


        <Topbar />


        <div className="main">
          <div className="left_side">
            <Leftdiv />
          </div>



          <div className="right_side">

            <div className="page_header"><CiBoxList size={28} />&nbsp; Public Quize</div>
            <div className='main_table'>

              <Table className="table">
                <thead>
                  <tr>
                    <th>SL</th>
                    <th style={{width:'50%'}}>Question</th>
                    <th>Answer</th>
                    <th>Date</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {
                    get_success_data.map((data, index) => {
                      if (data.actives === 0) {
                        return (
                          <tr key={index}>
                            <td>{a++}</td>
                            <td style={{width:'50%'}}>{data.question}</td>
                            <td>{data.answer}</td>
                            <td>{data.created_at.slice(0, 10)}</td>
                            <td>
                              <button className='quize_cata_delete_btn' onClick={() => quize_allowfunct(data)}>{data.actives === 1 ? "Registrated User" : "Public Allow"}</button>
                              <button className='quize_cata_delete_btn'>Delete</button>
                            </td>
                          </tr>
                        )
                      }
                    })
                  }
                </tbody>
              </Table>

            </div>

          </div>

        </div>


      </main>


    </>
  )
}
