import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import Link from 'next/link'
import { FaBars, FaTimes } from "react-icons/fa";
import React, { useState } from 'react';
import Header from './header/header';
import Jumboters_component from './header/Jumboters_component';
import Footer from './header/Footer';
import Slider_catagory from './header/Slider_catagory';




export default function Home() {

 



  return (
    <>
      <Head>
        <title>shikhonschool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
    <main>
      <Header/>
      <Jumboters_component/>      
      <Slider_catagory/>
      <Footer/>

      
      



    </main>

 
    </>
  )
}


